// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "d11ca2b25feaead11c7a9264c685d0b7"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"1560c81c19190a72ec1ed52fc27cda00": "1f8b08000000000000ff6c8fc16ac3300c86ef7e0a93bbc3d67b6e7b84dd4a0e7223626d8a2d6479b494befb70685907bdd9bfbeef473ac652be6767648c7ef2c3f53a7ef6f7ed36b805eb49498c4abe8f3efe920e30e4b5c1ba8b9807e78ea599341b936d3cbb0d2c7dc139d42652d4fce44d1bfea74661b808e6d9e1420671df62c7983286dcb6885a5fab15414f69764c1b5950ac8dada38737d72a86580a23e4007979f8b1946ae171ece1fe4f84da9b2e4f9980c2aa20c94ffedde1599e5a12c242790d55982c30fe2077f3370000fffff36bca634b010000",
		"48b73f4e90cd47a0067a27b6ca3cd05b": "1f8b08000000000000ff24cac10980300c05d0bb537cf0e0cd2ddcc00542fdd0484da04905b717f1f8e0cdd82cbb32a6bd6a205852dd50dc52d402d21ab212fc171e1fcb4d5c7210e91f3b4e1fdda4ad6f000000ffff2b531ff04c000000",
		"c31d041389a64373d81dad31c13c69a7": "1f8b08000000000000ff5256082ecdcd4d2caae4e2d2558876cd2b29ca4c2d8ed5488530f4835c1d5d7c5df5725334b914141414aaab158a12f3d25315f4146a6bc122ba0ad1d5d57abef9792519b5b5b11ad5d57a3e9979d9b5b510f5c83aa06643f5c174866496e4a4ba2496a48274c36cadaed673cb8409c32d071b969a9702b31ac1e302040000ffff8adf1618c6000000",
		"c5286b900d1ab10d2caf466035540c5b": "1f8b08000000000000ff5256a8ae56d073492c4955a8ade5e28a8f8fe7e2528608866496e44044413ca7fc944a85da5a40000000ffff8f0791dc30000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("data", "./data")
		b.SetResolver("SUMMARY.md", packr.Pointer{ForwardBox: gk, ForwardPath: "c31d041389a64373d81dad31c13c69a7"})
		b.SetResolver("book.toml", packr.Pointer{ForwardBox: gk, ForwardPath: "1560c81c19190a72ec1ed52fc27cda00"})
		b.SetResolver("entries/README.md", packr.Pointer{ForwardBox: gk, ForwardPath: "48b73f4e90cd47a0067a27b6ca3cd05b"})
		b.SetResolver("entries/entry.md", packr.Pointer{ForwardBox: gk, ForwardPath: "c5286b900d1ab10d2caf466035540c5b"})
		}()

	return nil
}()
